sudo: false
language: node_js
node_js:
- node
- lts/*
env:
  global:
  - secure: CTHiHBM7EACnBuN+hf146bQAQ0asVrDNM5u2vt1tI0HhCQ5IBLDxEGkZei55pLgz+iJnpTMaBoC3Lk+qTE9CxpHKPes5oGtfnBTcfmlzi17GmjVKy92ELQf+4uMNmRTmg6dlKgYpGaSOIiuVftOyUZo/Oc8sLyeMVAN9f/F2m/dGWte6MUn+pEGLZewSTlAAnUFFqIlHPgwGXVrQZnArcPWPpV7LDsdEOBPtcBsMXILwj43kKLh4ITQyRsMksI1OHRPHguuxbZ8yvwkDXBTXbAZ0Mc9Fn0IvHZacI1mKPqYRyIj9HzZZdZHb0u3lWLpQsBW7RPHZLUUY/Ag6aA2+ZLx1w6WHhqhsxObuSq+UKkkP32CwnKkJEZGv5T9QU54527SWrPe9Yt21vHKkZ73eBJhQNJ54zjo8pcKXAaq3qPgSRQtXaxyQ3tOqksMSweHfajtm2uRU07/B1noPzDumUjxZ2lPfMScQwRMrktezMx3/fsfxXzAyYxKH45Zr4+dkR1+Wp/54+UXrP0deYlAAIkldJpDB2f/mlAt1YrOxZwcC4UqEahL5Gi08Z+C0tj/p1ftTPIGcQI797r23t+OWkvOtngfQZESSE1G8MytURNS9SFORSIjy67x7v4jTV8F0n7PKiMWkxOM9PNohqwPNa3TrgSV431NAjdWhMoDCNio=
  - secure: V3hW9il/Ibb4MtKmSuanBSim3ucEjO7345RcBiHkHR1SqhABuhMnWH7dSSzdJe574/qGt1ch0nyiILf7wcGMSf7yTrF9bMCbUYmDhC9fmjZLkBpo7NTlEzECHNgGz3r05Xps9DTLBEjrJD44r8OM6U0zw2znBDXps6ILUF6q19/6+UE/39MmZngADcRTFk8TtxxMvRgZVU+tLxErbj52x1nB63JTBoYKN741JAK+/tUprilS0W24mkAvn+rUglH6jCS2gDmua2r+GPc3wqr1YPbuYlBX8KsI6d5+mAkAXjF8SFOFgCYimZO8Zrfmz74CI9nM2ovzv7ImpREvIrFM0A==
