sudo: false
language: node_js
node_js:
- node
- lts/*
env:
  global:
  - secure: l/x8huL1RfrYqsH3fUK108Lslm5uNg2HGQmgT7aGVziWbJSu2UGDh7yPaknFOsZC3w9SdoQ47SjCB712vqe47wHKAXWqKBP81JC4Y6w3/dgHd1WTnt/dWrEqmOHDvboXr0LbASZ4vOl5w3ljckO+Tqe1WrJ02NjolpxyYtFV2FS6GCdLFaSimxZc7F1QlmP4TG+iQ2sYUfr9VIDpMTlD5oblWOlQp6kyo4QsdF/YUB6xC/cIUBPoTWzSRqkCTrgktk0YqdR3GMLA3bV9VL5YLYwQIjNE9P6UC7fzyg3MZnxTtQ9SUBy9hJALmJi9+Aht0/Ugc29aofkVT/Pp5UwIh9Sqy3fg6/mG7/Csw4kKQ+qyBRNLRiWfVi+cpaAlOFslBrjTcXUdVX6DTeHZVjc1FaP0bQAAhksnR+KnM78lXBcTchI+0ngpKYHVnD/Da7r+mUt5SKTdHSCp7mzsXZPVVpLG9mKtI2OSl9sbkuWFOi6fPypgNPvpwCQj4M+lYi3NlQTHkZjN09mxycKPgjW68XmCieFzpQG4iaWIifPdeJmD7YDKe4dQegPXQ20/r1RS1oV9t7DwPLhltGb2G7b6ANtddBNpU4xtSBj5xa6SzWgjtrwsWKjY5LxkwYWTHL2RCTsYMjThJagW4dA8BpEpkfMCU1E6zTbDy/Vw8wJygmk=
