sudo: false
language: node_js
node_js:
- node
- lts/*
env:
  global:
  - secure: CTHiHBM7EACnBuN+hf146bQAQ0asVrDNM5u2vt1tI0HhCQ5IBLDxEGkZei55pLgz+iJnpTMaBoC3Lk+qTE9CxpHKPes5oGtfnBTcfmlzi17GmjVKy92ELQf+4uMNmRTmg6dlKgYpGaSOIiuVftOyUZo/Oc8sLyeMVAN9f/F2m/dGWte6MUn+pEGLZewSTlAAnUFFqIlHPgwGXVrQZnArcPWPpV7LDsdEOBPtcBsMXILwj43kKLh4ITQyRsMksI1OHRPHguuxbZ8yvwkDXBTXbAZ0Mc9Fn0IvHZacI1mKPqYRyIj9HzZZdZHb0u3lWLpQsBW7RPHZLUUY/Ag6aA2+ZLx1w6WHhqhsxObuSq+UKkkP32CwnKkJEZGv5T9QU54527SWrPe9Yt21vHKkZ73eBJhQNJ54zjo8pcKXAaq3qPgSRQtXaxyQ3tOqksMSweHfajtm2uRU07/B1noPzDumUjxZ2lPfMScQwRMrktezMx3/fsfxXzAyYxKH45Zr4+dkR1+Wp/54+UXrP0deYlAAIkldJpDB2f/mlAt1YrOxZwcC4UqEahL5Gi08Z+C0tj/p1ftTPIGcQI797r23t+OWkvOtngfQZESSE1G8MytURNS9SFORSIjy67x7v4jTV8F0n7PKiMWkxOM9PNohqwPNa3TrgSV431NAjdWhMoDCNio=
  - secure: dXuH8NS/JOz8qHrqiQBGAkp89qqnm+s1xsDdclIHbM5d1jGlmlcrlzD1kT8+eO4bs7LfCQVthUHdiiKve88JOlaiwgNZDCOt7wUy6LXni+cwXNIe1Y/R3Y/5V255z/y2L3jTzumesqCgQXlnE9bj1EApBL8q9MS9AMdfPIJtOL2LhI/zA22F015WiYOPQV8iGe9Mw8EY3BaAU4cMhYB5DUhUyjCjy2x9HKXvgrNPq6QFlede6evEmDAyAi8C+ICRonUE8Lk2OoAtaNeGEy+mani8pgLJoF+hdSrJWW2D2XU28JkiKgZ89ZJpB7x1l/5PNP0CXuvWSO9mT0PT2d+MaA==
